module.exports = {
    up: async (queryInterface) => {
      return queryInterface.bulkInsert('Users', [
        {
          UserName: 'johndoe@example.com',
          FName: 'John',
          LName: 'Doe',
          City: 'New York',
          State: 'NY',
          Country: 'USA',
          Email: 'johndoe@example.com',
          KTN: '1234567890',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'janedoe@example.com',
          FName: 'Jane',
          LName: 'Doe',
          City: 'Los Angeles',
          State: 'CA',
          Country: 'USA',
          Email: 'janedoe@example.com',
          KTN: '0987654321',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'bobsmith@example.com',
          FName: 'Bob',
          LName: 'Smith',
          City: 'Chicago',
          State: 'IL',
          Country: 'USA',
          Email: 'bobsmith@example.com',
          KTN: '1122334455',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'alicejones@example.com',
          FName: 'Alice',
          LName: 'Jones',
          City: 'Miami',
          State: 'FL',
          Country: 'USA',
          Email: 'alicejones@example.com',
          KTN: '5566778899',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'charliebrown@example.com',
          FName: 'Charlie',
          LName: 'Brown',
          City: 'Dallas',
          State: 'TX',
          Country: 'USA',
          Email: 'charliebrown@example.com',
          KTN: '6677889900',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'emilydavis@example.com',
          FName: 'Emily',
          LName: 'Davis',
          City: 'Boston',
          State: 'MA',
          Country: 'USA',
          Email: 'emilydavis@example.com',
          KTN: '3344556677',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'danielmiller@example.com',
          FName: 'Daniel',
          LName: 'Miller',
          City: 'San Francisco',
          State: 'CA',
          Country: 'USA',
          Email: 'danielmiller@example.com',
          KTN: '2233445566',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'sarahwilson@example.com',
          FName: 'Sarah',
          LName: 'Wilson',
          City: 'Seattle',
          State: 'WA',
          Country: 'USA',
          Email: 'sarahwilson@example.com',
          KTN: '4455667788',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'michaelclark@example.com',
          FName: 'Michael',
          LName: 'Clark',
          City: 'Austin',
          State: 'TX',
          Country: 'USA',
          Email: 'michaelclark@example.com',
          KTN: '8899001122',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserName: 'olivialewis@example.com',
          FName: 'Olivia',
          LName: 'Lewis',
          City: 'Denver',
          State: 'CO',
          Country: 'USA',
          Email: 'olivialewis@example.com',
          KTN: '5566771100',
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ]);
    },
    
    down: async (queryInterface) => {
      return queryInterface.bulkDelete('Users', null, {});
    }
  };
  